<?php
/**
 * Shadow-taxonomy link resolution for Post Terms Block Unlinked.
 *
 * @package PostTermsBlockUnlinked
 * @since   0.1.0
 */

declare(strict_types=1);

namespace PostTermsBlockUnlinked;

use GatherPress\Core;
use GatherPress\Core\Shadow_Source;
use WP_Block;
use WP_Term;

// Exit if accessed directly.
defined( 'ABSPATH' ) || exit; // @codeCoverageIgnore

/**
 * Rewrites shadow-taxonomy term links to their source post permalinks.
 *
 * @since 0.1.0
 */
class Shadow_Links {

	use Core\Traits\Singleton;

	/**
	 * Constructor — registers hooks.
	 *
	 * @since 0.1.0
	 */
	protected function __construct() {
		$this->setup_hooks();
	}

	/**
	 * Registers all hooks.
	 *
	 * @since 0.1.0
	 * @return void
	 */
	protected function setup_hooks(): void {
		add_filter( 'pre_render_block', array( $this, 'maybe_add_term_link_filter' ), 10, 2 );
	}

	/**
	 * Before a core/post-terms block renders, checks whether its taxonomy is
	 * a GatherPress shadow taxonomy. If so, adds a term_link filter for the
	 * duration of this block's render and removes it immediately after.
	 *
	 * Returns null in all cases so the block renders normally.
	 *
	 * @since 0.1.0
	 * @param string|null          $pre_render Null (no short-circuit).
	 * @param array<string, mixed> $block      Parsed block data.
	 * @return null
	 */
	public function maybe_add_term_link_filter( ?string $pre_render, array $block ): ?string {
		if ( 'core/post-terms' !== ( $block['blockName'] ?? '' ) ) {
			return $pre_render;
		}

		$taxonomy  = sanitize_key( $block['attrs']['term'] ?? '' );
		$post_type = $this->resolve_shadow_post_type( $taxonomy );

		if ( '' === $post_type ) {
			return $pre_render;
		}

		// Add the term_link filter just for this block's render.
		add_filter( 'term_link', array( $this, 'rewrite_term_link' ), 10, 2 );

		add_filter(
			'render_block_core/post-terms',
			function ( string $block_content ) use ( $taxonomy ): string {
				remove_filter( 'term_link', array( $this, 'rewrite_term_link' ), 10 );
				return $block_content;
			},
			0 // Priority 0 — runs first, before any other render_block filter.
		);

		return $pre_render;
	}

	/**
	 * Replaces a shadow-taxonomy term link with the source post's permalink.
	 *
	 * Hooked temporarily to `term_link` while a shadow-taxonomy post-terms
	 * block is rendering. Resolves the source post via Shadow_Source and
	 * returns its permalink. Falls back to the original $termlink unchanged
	 * when no source post can be found.
	 *
	 * @since 0.1.0
	 * @param string  $termlink The term archive URL generated by WordPress.
	 * @param WP_Term $term     The term object.
	 * @return string The source post permalink, or the original term link.
	 */
	public function rewrite_term_link( string $termlink, WP_Term $term ): string {
		$post_type   = $this->resolve_shadow_post_type( $term->taxonomy );
		$source_post = Shadow_Source::get_instance()->get_post_from_term_slug( $term->slug, $post_type );

		if ( null === $source_post ) {
			return $termlink;
		}

		return get_permalink( $source_post ) ?: $termlink;
	}

	/**
	 * Returns the shadow-source post type for a taxonomy slug, or '' if none.
	 *
	 * A taxonomy is a GP shadow taxonomy when its slug starts with '_' and
	 * the derived post type (slug minus the leading underscore) declares
	 * `gatherpress-shadow-source` support.
	 *
	 * @since 0.1.0
	 * @param string $taxonomy Taxonomy slug.
	 * @return string Source post type slug, or empty string.
	 */
	private function resolve_shadow_post_type( string $taxonomy ): string {
		if ( '' === $taxonomy || '_' !== $taxonomy[0] ) {
			return '';
		}

		$post_type = substr( $taxonomy, 1 );

		if ( ! post_type_supports( $post_type, 'gatherpress-shadow-source' ) ) {
			return '';
		}

		return $post_type;
	}
}
